---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: ubuntu-docker
    box: ubuntu/bionic64
    memory: 512
    cpus: 1
    provider_raw_config_args:
    - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
ansible:
  playbook: playbook.yml
  group_vars:
    all:
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/ubuntu-docker/virtualbox/private_key
scenario:
  name: default
lint:
  name: yamllint
  enabled: false
verifier:
  name: testinfra
  env:
    # get rid of the DeprecationWarning messages of third-party libs,
    # see https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint:
    name: flake8
